[package]
org = "evento-globolo"
name = "evgl-e2e"
version = "0.1.0"
description = "End-to-end integration package for Evento Globolo"
license = "MIT"
language = "polyglot"

[package.repository]
vcs = "git"
url = "https://github.com/evento-globolo/evgl-e2e"

[install]
dir = ".vendor/.zed"

[dependencies]
"evento-globolo/evgl-clients" = "^0.1.0"
"evento-globolo/evgl-interfaces" = "^0.1.0"
"evento-globolo/evgl-libs" = "^0.1.0"
"evento-globolo/evgl-cli" = "^0.1.0"
